################################################################################
#
################################################################################

apiVersion: batch/v1
kind: Job
metadata:
  name: always-fails
spec:
  backoffLimit: 0
  template:
    metadata:
      name: always-fails
    spec:
      restartPolicy: Never
      activeDeadlineSeconds: 120
      containers:
        - name: always-fails
          image: bash:5.0.17
          imagePullPolicy: IfNotPresent
          command:
            - /usr/local/bin/bash
            - /mnt/func-tests/src/script/test/always_fails.sh
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          volumeMounts:
            - name: func-tests
              mountPath: /mnt/func-tests
      volumes:
        - name: func-tests
          persistentVolumeClaim:
            claimName: func-tests
