################################################################################
#
################################################################################

apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-eos
spec:
  backoffLimit: 0
  template:
    metadata:
      name: k8s-eos
    spec:
      restartPolicy: Never
      activeDeadlineSeconds: 120
      securityContext:
        seLinuxOptions:
          type: "spc_t"
      volumes:
        - name: func-tests
          persistentVolumeClaim:
            claimName: func-tests
        - name: eos
          hostPath:
            path: /var/eos
      containers:
        - name: k8s-eos
          image: bash:5.0.17
          imagePullPolicy: IfNotPresent
          command:
            - /usr/local/bin/bash
            - /mnt/func-tests/src/script/test/k8s_eos.sh
          volumeMounts:
            - name: func-tests
              mountPath: /mnt/func-tests
            - name: eos
              mountPath: /eos
              mountPropagation: HostToContainer
