apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-eos
spec:
  backoffLimit: 0
  template:
    metadata:
      name: k8s-eos
    spec:
      restartPolicy: Never
      activeDeadlineSeconds: 120
      securityContext:
        seLinuxOptions:
          type: "spc_t"
      containers:
        - name: k8s-eos
          image: bash:5.0.17
          imagePullPolicy: IfNotPresent
          command:
            - "/usr/local/bin/bash"
            - "/mnt/gitlab-repo/src/script/k8s-eos.sh"
          volumeMounts:
            - name: gitlab-repo
              mountPath: /mnt/gitlab-repo
            - name: eos
              mountPath: /eos
              mountPropagation: HostToContainer
      volumes:
        - name: gitlab-repo
          hostPath:
            path: /mnt/gitlab-repo
        - name: eos
          hostPath:
            path: /var/eos
