################################################################################
#
################################################################################

apiVersion: argoproj.io/v1alpha1
kind: Workflow

################################################################################

metadata:
  generateName: dispatch-sample-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: ""

################################################################################

spec:

  ##############################################################################

  entrypoint: main

  ##############################################################################

  arguments:
    parameters:
      ##########################################################################
      - name: openstack_token
      ##########################################################################
      - name: gitlab_token
      - name: gitlab_url
        value: gitlab.cern.ch/kubernetes/testing/functional.git
      ##########################################################################
      - name: source_path
        value: /mnt/func-tests
      ##########################################################################
      - name: cluster_name
        value: "vsantaro-func-tests--test"
      - name: cluster_template
        value: "kubernetes-1.22.9-1"
      - name: cluster_node_count
        value: "4"
      - name: cluster_labels
        value: "KEY1=VALUE1,KEY2=VALUE2;KEY3=VALUE3"
      ##########################################################################
      - name: may_create_cluster
        value: "true"
      - name: may_fail_if_exists
        value: "false"
      - name: test_name

  ##############################################################################

  volumeClaimTemplates:
    - metadata:
        name: func-tests
      spec:
        accessModes: [ReadWriteMany]
        storageClassName: geneva-cephfs-testing
        resources:
          requests:
            storage: 1Gi

  ##############################################################################

  templates:

    ############################################################################

    - name: main
      steps:
        - - name: clone-repo
            template: clone-repo
            arguments:
              parameters:
                - name: gitlab_token
                  value: "{{workflow.parameters.gitlab_token}}"
                - name: gitlab_url
                  value: "{{workflow.parameters.gitlab_url}}"
                - name: source_path
                  value: "{{workflow.parameters.source_path}}"
        - - name: maybe_create_cluster
            template: maybe-create-cluster
            arguments:
              parameters:
                - name: openstack_token
                  value: "{{workflow.parameters.openstack_token}}"
                - name: source_path
                  value: "{{workflow.parameters.source_path}}"
        # - - name: wait-cluster-ready
        #     template: wait-cluster-ready
        #     arguments:
        #       parameters:
        #         - name: os_token
        #           value: "{{workflow.parameters.os_token}}"
        # - - name: exec-test
        #     template: exec-test
        #     arguments:
        #       parameters:
        #         - name: os_token
        #           value: "{{workflow.parameters.os_token}}"
        #         - name: test-name
        #           value: "{{workflow.parameters.test-name}}"
        - - name: delete-cluster
            template: delete-cluster
            when: |
              {{steps.maybe_create_cluster.outputs.created_cluster}} == true
            arguments:
              parameters:
                - name: openstack_token
                  value: "{{workflow.parameters.openstack_token}}"

    ############################################################################

    - name: clone-repo
      inputs:
        parameters:
          - name: gitlab_token
          - name: gitlab_url
          - name: source_path
      script:
        image: registry.cern.ch/vsantaro/func-tests
        volumeMounts:
          - name: func-tests
            mountPath: "{{inputs.parameters.source_path}}"
        command: [/bin/bash]
        env:
          - name: gitlab_token
            value: "{{inputs.parameters.gitlab_token}}"
          - name: gitlab_url
            value: "{{inputs.parameters.gitlab_url}}"
          - name: source_path
            value: "{{inputs.parameters.source_path}}"
        source: |
          #!/bin/bash

          set -ex

          git clone \
            "https://oauth2:${gitlab_token}@${gitlab_url}" \
            --branch vitorsrg \
            --single-branch \
            --depth 1 \
            ${source_path}

    ############################################################################

    - name: maybe-create-cluster
      inputs:
        parameters:
          - name: openstack_token
          - name: source_path
          - name: cluster_name
          - name: cluster_template
          - name: cluster_node_count
          - name: cluster_labels
          - name: may_create_cluster
          - name: may_fail_if_exists
      outputs:
        parameters:
          - name: cluster_uuid
            valueFrom:
              path: /root/output/cluster_uuid.txt
          - name: created_cluster
            valueFrom:
              path: /root/output/created_cluster.txt
      container:
        image: registry.cern.ch/vsantaro/func-tests
        volumeMounts:
          - name: func-tests
            mountPath: "{{inputs.parameters.source_path}}"
        command: [/bin/bash]
        args:
          - /mnt/gitlab-repo/src/script/workflow/create_cluster.sh
        env:
          - name: openstack_token
            value: "{{inputs.parameters.openstack_token}}"
          - name: source_path
            value: "{{inputs.parameters.source_path}}"
          - name: cluster_name
            value: "{{inputs.parameters.cluster_name}}"
          - name: cluster_template
            value: "{{inputs.parameters.cluster_template}}"
          - name: cluster_node_count
            value: "{{inputs.parameters.cluster_node_count}}"
          - name: cluster_labels
            value: "{{inputs.parameters.cluster_labels}}"
          - name: may_create_cluster
            value: "{{inputs.parameters.may_create_cluster}}"
          - name: may_fail_if_exists
            value: "{{inputs.parameters.may_fail_if_exists}}"

    ############################################################################

    # - name: wait-cluster-ready
    #   inputs:
    #     parameters:
    #       - name: os_token
    #   container:
    #     image: registry.cern.ch/vsantaro/func-tests
    #     volumeMounts:
    #       - name: gitlab-repo
    #         mountPath: /mnt/gitlab-repo
    #     command: [/bin/bash]
    #     args:
    #       - /mnt/gitlab-repo/src/script/workflow/wait_cluster_ready.sh
    #     env:
    #       - name: OS_TOKEN
    #         value: "{{inputs.parameters.os_token}}"

    ############################################################################

    # - name: exec-test
    #   inputs:
    #     parameters:
    #       - name: os_token
    #       - name: test-name
    #   outputs:
    #     parameters:
    #       - name: test_result
    #         valueFrom:
    #           default: unknown
    #           path: /root/test_result.txt
    #   container:
    #     image: registry.cern.ch/vsantaro/func-tests
    #     volumeMounts:
    #       - name: gitlab-repo
    #         mountPath: /mnt/gitlab-repo
    #     command: [/bin/bash]
    #     args:
    #       - /mnt/gitlab-repo/src/script/workflow/exec_test.sh
    #     env:
    #       - name: OS_TOKEN
    #         value: "{{inputs.parameters.os_token}}"
    #       - name: test_name
    #         value: "{{inputs.parameters.test-name}}"

    ############################################################################

    - name: delete-cluster
      inputs:
        parameters:
          - name: openstack_token
          - name: source_path
      container:
        image: registry.cern.ch/vsantaro/func-tests
        volumeMounts:
          - name: func-tests
            mountPath: "{{inputs.parameters.source_path}}"
        command: [/bin/bash]
        args:
          - /mnt/gitlab-repo/src/script/workflow/delete_cluster.sh
        env:
          - name: openstack_token
            value: "{{inputs.parameters.openstack_token}}"
          - name: source_path
            value: "{{inputs.parameters.source_path}}"
