################################################################################
#
################################################################################

apiVersion: v1
kind: Pod
metadata:
  name: always-fails
spec:
  containers:
    - name: main
      image: bash:5.0.17
      command:
        - /usr/local/bin/bash
        - "${source_path}/src/script/test/always_fails.sh"
      env:
        - name: source_path
          value: "!ch.cern{source_path}"
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "4Gi"
          cpu: "1"
      volumeMounts:
        - name: func-tests-src
          mountPath: "!ch.cern{source_path}"
          readOnly: true
  volumes:
    - name: func-tests-src
      configMap:
        name: func-tests-src
        items: []
