################################################################################
#
################################################################################

apiVersion: v1
kind: Pod
metadata:
  name: k8s-eos
spec:
  securityContext:
    seLinuxOptions:
      type: "spc_t"
  containers:
    - name: main
      image: bash:5.0.17
      imagePullPolicy: IfNotPresent
      command:
        - /usr/local/bin/bash
        - /mnt/func-tests-src/src/script/test/k8s_eos.sh
      env:
        - name: source_path
          value: /mnt/func-tests-src
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "4Gi"
          cpu: "1"
      volumeMounts:
        - name: func-tests-src
          mountPath: /mnt/func-tests-src
          readOnly: true
        - name: eos
          mountPath: /eos
          mountPropagation: HostToContainer
  volumes:
    - name: func-tests-src
      configMap:
        name: func-tests-src
        items: []
    - name: eos
      hostPath:
        path: /var/eos
